
import { Car, Message, Notification, Reservation, User, ReservationStatus } from "./types";

// Mock Users
export const users: User[] = [
  {
    id: "user-1",
    role: "client",
    email: "client@example.com",
    firstName: "Ahmed",
    lastName: "Ben Ali",
    phoneNumber: "12345678",
    postalCode: "1000",
    address: "20 Avenue Habib Bourguiba, Tunis",
    cinPassport: "12345678",
    profilePicture: "/placeholder.svg",
    notificationPreferences: {
      email: true,
      browser: true,
      sms: false,
    },
    createdAt: "2023-01-15T12:00:00.000Z",
  },
  {
    id: "user-2",
    role: "client",
    email: "sarra@example.com",
    firstName: "Sarra",
    lastName: "Mansouri",
    phoneNumber: "23456789",
    postalCode: "2083",
    address: "15 Rue de Marseille, Tunis",
    cinPassport: "23456789",
    profilePicture: "/placeholder.svg",
    notificationPreferences: {
      email: true,
      browser: false,
      sms: true,
    },
    createdAt: "2023-02-20T09:30:00.000Z",
  },
  {
    id: "admin-1",
    role: "admin",
    email: "admin@autowise.com",
    firstName: "Mohamed",
    lastName: "Trabelsi",
    phoneNumber: "98765432",
    createdAt: "2022-12-01T10:00:00.000Z",
    profilePicture: "/placeholder.svg",
  },
];

// Mock Cars
export const cars: Car[] = [
  {
    id: "car-1",
    brand: "Renault",
    model: "Clio",
    year: 2022,
    transmission: "manuel",
    fuelType: "essence",
    seats: 5,
    dailyPrice: 75,
    hasAC: true,
    hasGPS: false,
    childSeatAvailable: true,
    driverAvailable: true,
    description: "Parfaite pour la ville, économique et compacte. Idéale pour les déplacements quotidiens dans Tunis.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    availability: {
      available: true,
      availableDates: [
        {
          startDate: "2023-05-01T00:00:00.000Z",
          endDate: "2023-12-31T00:00:00.000Z",
        },
      ],
    },
    features: ["Radio", "Bluetooth", "USB", "Airbags"],
    category: "économique",
  },
  {
    id: "car-2",
    brand: "Volkswagen",
    model: "Golf",
    year: 2021,
    transmission: "automatique",
    fuelType: "diesel",
    seats: 5,
    dailyPrice: 120,
    hasAC: true,
    hasGPS: true,
    childSeatAvailable: true,
    driverAvailable: false,
    description: "Confort et performance pour tous vos déplacements. Un excellent choix pour explorer la Tunisie.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    availability: {
      available: true,
      availableDates: [
        {
          startDate: "2023-05-01T00:00:00.000Z",
          endDate: "2023-12-31T00:00:00.000Z",
        },
      ],
    },
    features: ["Climatisation", "GPS intégré", "Camera de recul", "Système audio premium"],
    category: "standard",
  },
  {
    id: "car-3",
    brand: "Mercedes",
    model: "Classe C",
    year: 2023,
    transmission: "automatique",
    fuelType: "hybride",
    seats: 5,
    dailyPrice: 250,
    hasAC: true,
    hasGPS: true,
    childSeatAvailable: true,
    driverAvailable: true,
    description: "Luxe et prestige pour vos événements spéciaux. Une expérience de conduite exceptionnelle.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    availability: {
      available: true,
      availableDates: [
        {
          startDate: "2023-05-01T00:00:00.000Z",
          endDate: "2023-12-31T00:00:00.000Z",
        },
      ],
    },
    features: [
      "Sièges en cuir",
      "Système audio Burmester",
      "Toit ouvrant panoramique",
      "Assistance à la conduite",
    ],
    category: "luxe",
  },
  {
    id: "car-4",
    brand: "Peugeot",
    model: "Partner",
    year: 2022,
    transmission: "manuel",
    fuelType: "diesel",
    seats: 3,
    dailyPrice: 100,
    hasAC: true,
    hasGPS: false,
    childSeatAvailable: false,
    driverAvailable: false,
    description: "Véhicule utilitaire spacieux, parfait pour les déménagements ou transport de marchandises.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    availability: {
      available: true,
      availableDates: [
        {
          startDate: "2023-05-01T00:00:00.000Z",
          endDate: "2023-12-31T00:00:00.000Z",
        },
      ],
    },
    features: ["Volume de chargement important", "Portes latérales coulissantes", "Économique"],
    category: "utilitaire",
  },
  {
    id: "car-5",
    brand: "BMW",
    model: "Série 5",
    year: 2023,
    transmission: "automatique",
    fuelType: "essence",
    seats: 5,
    dailyPrice: 280,
    hasAC: true,
    hasGPS: true,
    childSeatAvailable: true,
    driverAvailable: true,
    description: "Alliance parfaite entre sportivité et élégance. Pour une expérience de conduite incomparable.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    availability: {
      available: true,
      availableDates: [
        {
          startDate: "2023-05-01T00:00:00.000Z",
          endDate: "2023-12-31T00:00:00.000Z",
        },
      ],
    },
    features: [
      "Sièges chauffants",
      "Tableau de bord numérique",
      "Systèmes d'aide à la conduite avancés",
    ],
    category: "luxe",
  },
  {
    id: "car-6",
    brand: "Dacia",
    model: "Sandero",
    year: 2022,
    transmission: "manuel",
    fuelType: "essence",
    seats: 5,
    dailyPrice: 65,
    hasAC: true,
    hasGPS: false,
    childSeatAvailable: true,
    driverAvailable: false,
    description: "Simple, fiable et économique. Le choix malin pour un budget limité.",
    images: [
      "/placeholder.svg",
      "/placeholder.svg",
    ],
    availability: {
      available: true,
      availableDates: [
        {
          startDate: "2023-05-01T00:00:00.000Z",
          endDate: "2023-12-31T00:00:00.000Z",
        },
      ],
    },
    features: ["Économique", "Spacieuse", "Fiable", "Faible consommation"],
    category: "économique",
  },
];

// Mock Reservations
export const reservations: Reservation[] = [
  {
    id: "res-1",
    userId: "user-1",
    carId: "car-1",
    startDate: "2023-06-05T10:00:00.000Z",
    endDate: "2023-06-08T18:00:00.000Z",
    totalPrice: 225,
    status: "confirmed" as ReservationStatus,
    withDriver: false,
    withChildSeat: false,
    withGPS: false,
    paymentMethod: "Carte bancaire",
    createdAt: "2023-05-28T15:30:00.000Z",
  },
  {
    id: "res-2",
    userId: "user-1",
    carId: "car-3",
    startDate: "2023-07-12T09:00:00.000Z",
    endDate: "2023-07-15T19:00:00.000Z",
    totalPrice: 750,
    status: "completed" as ReservationStatus,
    withDriver: true,
    withChildSeat: false,
    withGPS: true,
    paymentMethod: "Espèces",
    createdAt: "2023-07-01T10:45:00.000Z",
  },
  {
    id: "res-3",
    userId: "user-2",
    carId: "car-2",
    startDate: "2023-08-20T08:00:00.000Z",
    endDate: "2023-08-25T20:00:00.000Z",
    totalPrice: 600,
    status: "pending" as ReservationStatus,
    withDriver: false,
    withChildSeat: true,
    withGPS: true,
    createdAt: "2023-08-10T14:20:00.000Z",
  },
];

// Mock Messages
export const messages: Message[] = [
  {
    id: "msg-1",
    senderId: "user-1",
    receiverId: "admin-1",
    content: "Bonjour, est-ce possible d'avoir un siège bébé supplémentaire pour ma réservation ?",
    timestamp: "2023-06-02T09:15:00.000Z",
    read: true,
  },
  {
    id: "msg-2",
    senderId: "admin-1",
    receiverId: "user-1",
    content: "Bonjour, oui c'est possible. Nous ajouterons cela à votre réservation avec un supplément de 10 TND par jour.",
    timestamp: "2023-06-02T10:30:00.000Z",
    read: true,
  },
  {
    id: "msg-3",
    senderId: "user-2",
    receiverId: "admin-1",
    content: "Je voudrais savoir si je peux prolonger ma location actuelle de 2 jours ?",
    timestamp: "2023-08-22T16:45:00.000Z",
    read: false,
  },
];

// Mock Notifications
export const notifications: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    title: "Réservation confirmée",
    content: "Votre réservation de Renault Clio a été confirmée pour le 5 juin.",
    read: true,
    type: "réservation",
    timestamp: "2023-05-28T15:35:00.000Z",
  },
  {
    id: "notif-2",
    userId: "user-1",
    title: "Rappel de retour",
    content: "Rappel: Votre location se termine demain à 18h00.",
    read: false,
    type: "réservation",
    timestamp: "2023-06-07T12:00:00.000Z",
  },
  {
    id: "notif-3",
    userId: "user-2",
    title: "Promotion spéciale",
    content: "Profitez de 15% de réduction sur votre prochaine location en utilisant le code SUMMER23.",
    read: false,
    type: "promotion",
    timestamp: "2023-08-15T08:00:00.000Z",
  },
  {
    id: "notif-4",
    userId: "admin-1",
    title: "Nouvelle réservation",
    content: "Nouvelle réservation reçue pour une Golf. En attente de confirmation.",
    read: false,
    type: "réservation",
    timestamp: "2023-08-10T14:25:00.000Z",
  },
];
